### ISSUE TITLE
todo for paper ready cogsci paper

### ISSUE THREAD

**Issue by dyurovsky** [FlamingoZh/FirstYearProject#1]
- [ ] fix authors to be one line
- [ ] write something about structural aspects of verb meaning
- [ ] tidy up repo, rename it, and fix link in paper
- [ ]  expand discussion to say more about video
